Master
qdrant/landing_page pull request #1131
Opened 2024-08-27 19:09 UTC by iamdorsa

The Qdrant documentation incorrectly describes a parameter named max_segment_number under the "Merge Optimizer" section, suggesting that this parameter controls the merging of small segments when their number exceeds a certain threshold. However, this parameter does not exist in the Qdrant codebase. Instead, the correct approach to managing segment size and merging is through the max_segment_size parameter, which determines the maximum size of a segment.

This discrepancy may have caused confusion among users trying to optimize their Qdrant instances, leading to ineffective configurations and potentially suboptimal performance.

2024-09-10 09:02 UTC, timvisee requested changes
Thanks for catching this!

While this is not entirely true, you're definitely right that `max_segment_number` is not a thing anymore.

Please see my comments below:

2024-09-11 14:18 UTC, iamdorsa commented on qdrant-landing/content/documentation/concepts/optimizer.md
> +Qdrant uses a parameter called max_segment_size to control the size of segments. Increasing this value allows the creation of larger segments, reducing the number of segments and potentially improvin
Yes, I will update it as soon as possible.

2024-09-11 15:21 UTC, timvisee commented on qdrant-landing/content/documentation/concepts/optimizer.md
> +Qdrant uses a parameter called max_segment_size to control the size of segments. Increasing this value allows the creation of larger segments, reducing the number of segments and potentially improvin
Thank you very much! :smile: 

I did notice we still had some mentions in the Qdrant repository. I've fixed this yesterday: https://github.com/qdrant/qdrant/pull/5058

2024-11-27 15:59 UTC, timvisee commented on qdrant-landing/content/documentation/concepts/optimizer.md
> +Qdrant uses a parameter called max_segment_size to control the size of segments. Increasing this value allows the creation of larger segments, reducing the number of segments and potentially improvin
```suggestion
The merge optimizer constantly tries to reduce the number of segments if there
currently are too many. The desired number of segments is specified
with `default_segment_number` and defaults to the number of CPUs. The optimizer
may takes at least the three smallest segments and merges them into one.

Segments will not be merged if they'll exceed the maximum configured segment
size with `max_segment_size_kb`. It prevents creating segments that are too
large to efficiently index. Increasing this number may help to reduce the number
of segments if you have a lot of data, and can potentially improve search performance.
```

2024-11-27 16:00 UTC, timvisee approved these changes

2024-11-27 17:01 UTC, merged