create cross-encoder-integration-gsoc
qdrant/landing_page pull request #1155
Opened 2024-09-09 14:57 UTC by celinehoang177

Create article 'Qdrant Summer of Code 2024 - ONNX Cross Encoders in Python' by Celine Hoang

2024-09-24 18:43 UTC, sabrinaaquino requested changes
Use this as social preview:

![social_preview](https://github.com/user-attachments/assets/845a1bba-18ba-43f8-9b46-3f789a76a09e)

2024-10-01 21:15 UTC, joein requested changes

2024-10-01 21:15 UTC, joein commented on qdrant-landing/content/articles/cross-encoder-integration-gsoc.md
> +Hi everyone! I’m Huong (Celine) Hoang, and I’m thrilled to share my experience working at Qdrant this summer as part of their Summer of Code 2024 program. During my internship, I worked on integratin
```suggestion
Hi everyone! I’m Huong (Celine) Hoang, and I’m thrilled to share my experience working at Qdrant this summer as part of their Summer of Code 2024 program. During my internship, I worked on integrating cross-encoders into the FastEmbed library for re-ranking tasks. This enhancement widened the capabilities of the Qdrant ecosystem, enabling developers to build more context-aware search applications, such as question-answering systems, using Qdrant's suite of libraries.
```

2024-10-01 21:15 UTC, joein commented on qdrant-landing/content/articles/cross-encoder-integration-gsoc.md
> +Qdrant is well-known for its vector search capabilities, but my task was to go one step further—introducing cross-encoders for re-ranking. Traditionally, the FastEmbed library would generate embeddin
```suggestion
Qdrant is well known for its vector search capabilities, but my task was to go one step further — introducing cross-encoders for re-ranking. Traditionally, the FastEmbed library would generate embeddings, but cross-encoders don’t do that. Instead, they provide a list of scores based on how well a query matches a list of documents. This kind of re-ranking is critical when you want to refine search results and bring the most relevant answers to the top.
```

2024-10-01 21:15 UTC, joein commented on qdrant-landing/content/articles/cross-encoder-integration-gsoc.md
> +An important point to mention is that FastEmbed is a minimalistic library—it doesn’t have heavy dependencies like PyTorch or TensorFlow, and as a result, it is lightweight, occupying far less storage
```suggestion
An important point to mention is that FastEmbed is a minimalistic library: it doesn’t have heavy dependencies like PyTorch or TensorFlow, and as a result, it is lightweight, occupying far less storage space.
```

2024-10-01 21:15 UTC, joein commented on qdrant-landing/content/articles/cross-encoder-integration-gsoc.md
> +FastEmbed already had support for embeddings, but re-ranking with cross-encoders meant building a completely new family of classes. These models accept a query and a set of documents, then return a l
```suggestion
FastEmbed already had support for embeddings, but re-ranking with cross-encoders meant building a completely new family of classes. These models accept a query and a set of documents, then return a list of relevance scores. For that, I created the base classes like `TextCrossEncoderBase` and `OnnxCrossEncoder`, taking inspiration from existing text embedding models.
```

2024-10-01 21:15 UTC, joein commented on qdrant-landing/content/articles/cross-encoder-integration-gsoc.md
> +Efficient tokenization is critical to ensure the performance of the models, and I optimized it specifically for ONNX models. The lightweight nature of FastEmbed means that it runs efficiently even wi
Has already been mentioned

```suggestion
Efficient tokenization is critical to ensure the performance of the models, and I optimized it specifically for ONNX models.
```

2024-10-01 21:15 UTC, joein commented on qdrant-landing/content/articles/cross-encoder-integration-gsoc.md
> +This rigorous testing process helped ensure that the ONNX models behaved as expected, comparable to models implemented using PyTorch.
```suggestion
The `CANONICAL_SCORE_VALUES` were retrieved directly from the result of applying the original PyTorch models to the same input
```

2024-10-14 12:51 UTC, joein approved these changes
Not sure about the weight which should be assigned to the article
@sabrinaaquino could you please take a look?

2024-10-14 18:36 UTC, sabrinaaquino approved these changes
lgtm

2024-10-14 18:37 UTC, merged