docs: update jina embeddings integration
qdrant/landing_page pull request #1164
Opened 2024-09-12 12:06 UTC by bwanglzu

Update documentation of jina embeddings:

1. Created a detailed model list with tech summary.
2. add description of task adapters of `jina-embeddings-v3` and how to use them.
3. add short description of MRL performance to give user a hint how to balance between storage and performance.
4. updated code snnipt.

2024-09-12 12:33 UTC, CatStark requested changes

2024-09-12 12:33 UTC, CatStark commented on qdrant-landing/content/documentation/embeddings/jina-embeddings.md
> +|  jina-embeddings-v2-base-de |  768 |  Spanish & English |  No  |  8192 |
```suggestion
|  jina-embeddings-v2-base-es |  768 |  Spanish & English |  No  |  8192 | 
```

2024-09-13 15:25 UTC, Anush008 commented on qdrant-landing/content/documentation/embeddings/jina-embeddings.md
> +Qdrant has been integrated with [Jina AI](https://jina.ai/). You need an API key from [Jina AI](https://jina.ai/embeddings/) to get embeddings.
```suggestion
Qdrant is compatible with [Jina AI](https://jina.ai/) embeddings. You need an API key from [Jina AI](https://jina.ai/embeddings/) to get embeddings.
```

2024-09-13 15:25 UTC, Anush008 commented on qdrant-landing/content/documentation/embeddings/jina-embeddings.md
> +> We recommend using `jina-embeddings-v3` as it is the latest and most performant embedding model released by Jina AI.
```suggestion
> Jina recommend using `jina-embeddings-v3` as it is the latest and most performant embedding model released by Jina AI.
```

2024-09-13 15:27 UTC, Anush008 commented on qdrant-landing/content/documentation/embeddings/jina-embeddings.md
>  # You can get a free trial key here: https://jina.ai/embeddings/
Probably mention the free trial in the texts above instead of this comment.

2024-09-16 06:53 UTC, Anush008 commented on qdrant-landing/content/documentation/embeddings/jina-embeddings.md
> +> Jina recommend using `jina-embeddings-v3` as it is the latest and most performant embedding model released by Jina AI.
```suggestion
> Jina recommends using `jina-embeddings-v3` as it is the latest and most performant embedding model released by Jina AI.
```

2024-09-16 07:29 UTC, bwanglzu commented
@Anush008 thanks for your review, please do not merge right now we might make a small change to api schema

2024-09-16 08:49 UTC, bwanglzu commented
@Anush008 PR updated, two small changes since last review:

1. rename `task_type` to `task` to adopt API change.
2. remove "free api key" from the code sample

2024-09-16 08:58 UTC, Anush008 commented on qdrant-landing/content/documentation/embeddings/jina-embeddings.md
> +## Guide
```suggestion
## Example
```

2024-09-16 09:00 UTC, Anush008 commented on qdrant-landing/content/documentation/embeddings/jina-embeddings.md
> +For Qdrant users, use code **QDRANT** for a 10% discount on Jina AI APIs.
```suggestion
Qdrant users can receive a 10% discount on Jina AI APIs by using the code **QDRANT**.
```

2024-09-16 09:15 UTC, Anush008 approved these changes
Thank you.

2024-09-16 09:15 UTC, merged