[WIP] HF Spaces demo post
qdrant/landing_page pull request #121
Opened 2023-03-23 05:41 UTC by monatis

It's a draft, and I'll request a review when it's done.

2023-03-23 09:17 UTC, generall commented
Images are not displaying anywhere: 
- empty image on the blog post cover
- empty images on the HF search result

2023-03-23 09:20 UTC, monatis commented
Looking into it.

2023-03-23 09:55 UTC, monatis commented
Found the root causes of both, fixing.

2023-03-27 07:12 UTC, monatis commented
Fixed both. Ready for review.

2023-03-28 09:24 UTC, kacperlukawski requested changes
Looks fine to me, I made some minor comments only. I'd like to know about the demo layout. Right now, search results are displayed in the right column, and that requires scrolling the page down over and over. Can we maybe make the search options centred and display the results under the search bar? So the images are displayed in 3-4 columns, and the page is just shorter.

2023-03-28 19:21 UTC, monatis commented on qdrant-landing/content/articles/hf-spaces-demo.md
> +weight: 10
I Set it to 1, as the most recent was 2.

2023-03-28 19:22 UTC, monatis commented on qdrant-landing/content/articles/hf-spaces-demo.md
> +Do not include the protocol prefix `https://` in the host value, e.g., `{cluster_id}.us-east-1-0.aws.cloud.qdrant.io`.
Fixed.

2024-07-02 19:33 UTC, closed without merging