Optimizing ColPali for Retrieval at Scale
qdrant/landing_page pull request #1323
Opened 2024-11-27 04:53 UTC by sabrinaaquino

2024-11-27 23:00 UTC, sabrinaaquino commented on qdrant-landing/content/blog/colpali-optimization.md
> +32 vectors represent the pooled rows, while an additional 6 vectors encode contextual information derived from ColPali’s special tokens (e.g., <bos> for the beginning of the sequence, and task-specif
Last of 38 of 1030?

2024-11-28 14:58 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
> +32 vectors represent the pooled rows, while an additional 6 vectors encode contextual information derived from ColPali’s special tokens (e.g., <bos> for the beginning of the sequence, and task-specif
Both, actually
I take last 6 vectors out of 1030, do mean/max pooling on 1024, converting them to 32, and then append 6 reamining ones, making 38 in total

2024-11-29 12:18 UTC, mrscoopers requested changes

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
We can add also pdf, vrag, visual RAG

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
> +$$
10^12

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
quadratically... with amount of multivectors per page

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
>  Pooling is well-known in machine learning as a way to compress data while keeping important information intact. For ColPali, we reduced ~1,030 vectors per page to just 38 vectors by pooling rows in t
I'd remove "intact"

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
>  Pooling is well-known in machine learning as a way to compress data while keeping important information intact. For ColPali, we reduced ~1,030 vectors per page to just 38 vectors by pooling rows in t
Also it's exactly 1030 per page

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
> +32 vectors represent the pooled rows, while the final 6 vectors encode contextual information derived from ColPali’s special tokens (e.g., <bos> for the beginning of the sequence, and task-specific i
I think "final" might be misunderstood as "we have 6 vectors as a final result"

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
>  ![](/blog/colpali-optimization/rows.png)
I feel like maybe image should come earlier, where we talk about pooling first time

2024-11-29 12:18 UTC, mrscoopers commented on qdrant-landing/content/blog/colpali-optimization.md
>  - **Full-Resolution Embeddings:** ~1,030 vectors per page.
exactly 1030

2024-11-30 21:38 UTC, sabrinaaquino commented on qdrant-landing/content/blog/colpali-optimization.md
We'll have a new blog for the RAG

2024-12-02 13:39 UTC, mrscoopers approved these changes

2024-12-02 13:54 UTC, merged