New post: Why Rust?
qdrant/landing_page pull request #135
Opened 2023-05-10 16:26 UTC by llogiq

Here's the article. Perhaps someone finds a better preview image? I just took the official Rust logo as a placeholder.

2023-05-10 16:33 UTC, generall commented on qdrant-landing/content/articles/why-rust.md
> +(Please note that the performance difference is not only down to the languages used, the implementations differ in algorithms and design tradeoffs. As always, use your own best judgement.)
let's remove, maybe? I don't think the main factor is the language in this particular case

2023-05-11 07:21 UTC, llogiq commented
Adressed the comments here and on slack. https://deploy-preview-135--condescending-goldwasser-91acf0.netlify.app/articles/why-rust/ now shows the preview image (although we may want to go more fancy?) and I removed the benchmark table.

2023-05-11 11:33 UTC, kacperlukawski requested changes
It would be good to introduce more headers in the text, as it would be easier to follow.

2023-05-11 11:47 UTC, kacperlukawski approved these changes

2023-05-11 11:48 UTC, kacperlukawski commented
We can just use a picture generated by Midjourney as a preview image

2023-05-16 08:12 UTC, merged