fix qdrant cloud quickstart documentation
qdrant/landing_page pull request #184
Opened 2023-06-13 13:19 UTC by davidmyriel

-update steps taken to spin up instance, authentication made clearer 
-overall edits and fixes in line with technical writing standards
-will add more images, still a draft

2023-06-13 14:10 UTC, kacperlukawski requested changes
Just two minor comments

2023-06-13 14:10 UTC, kacperlukawski commented on qdrant-landing/content/documentation/cloud/cloud-quick-start.md
> +4. In the Beta version, you can only deploy to AWS. We are currentl;y developing support GCP and Azure.
"currentl;y"?

2023-06-13 14:10 UTC, kacperlukawski commented on qdrant-landing/content/documentation/cloud/cloud-quick-start.md
> +> Each node is automatically attached with a disc space offering enough space for your data if you decide to put the metadata or even the index on the disc storage.
Shouldn't it be "disk space", not "disc space"?

2023-06-13 14:15 UTC, fabriziobonavita reviewed
Fantastic, thank you, left some comments

2023-06-14 09:40 UTC, kacperlukawski reviewed
Just one minor comment

2023-06-14 09:40 UTC, kacperlukawski commented on qdrant-landing/content/documentation/cloud/cloud-quick-start.md
> +> Each node is automatically attached with a disk space offering enough space for your data if you decide to put the metadata or even the index on the disc storage.
There is also "disc storage", which should be changed to "disk storage"

2023-06-14 12:22 UTC, davidmyriel commented
should be good to go

2023-06-14 12:28 UTC, kacperlukawski requested changes
Looks good!

2023-06-14 12:29 UTC, kacperlukawski approved these changes

2023-06-14 13:50 UTC, merged