[wip] quickstart langchain
qdrant/landing_page pull request #304
Opened 2023-09-12 11:46 UTC by davidmyriel

-wrote code
-added to QuickStarts in documentation
-still need to do some more storytelling and add the sample doc

2023-09-12 12:46 UTC, kacperlukawski requested changes
There are some minor comments, but overall, it's a good starting point. I'd love to see the content of the `document.txt` and the app's outputs. Otherwise, I have no idea if the answers are accurate.

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +```
If those code snippets are put next to each other, they are rendered as tabs.
![image](https://github.com/qdrant/landing_page/assets/2649301/a8f68d5b-b921-46ae-a73f-eba9ca0fe73a)
It feels like we have to choose one of the options, but in reality, we need to make both steps.

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +    )
There is unnecessary indentation here.

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +    )
There is unnecessary indentation here.

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +    )
There is unnecessary indentation here. Also, an additional space, it should be `collection_name=QDRANT_COLLECTION_NAME` instead

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +```
Again, it's rendered as tabs.

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +    )
How about setting the host and API key directly in `QdrantClient`? The env variables are not required

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +    collection_name=os.getenv("QDRANT_COLLECTION"),
The env variable is not set before. Shouldn't the `collection_name` be set to `QDRANT_COLLECTION_NAME`?

2023-09-12 12:46 UTC, kacperlukawski commented on qdrant-landing/content/documentation/quickstart/quickstart-langchain.md
> +vectorstore.add_texts(texts)
The notebook could be simplified by using `Qdrant.from_texts`, so Langchain will handle the creation of the collection.

2025-01-15 02:35 UTC, davidmyriel commented
out of date

2025-01-15 02:35 UTC, closed without merging