WIP: Add short move shards guide
qdrant/landing_page pull request #395
Opened 2023-11-07 15:13 UTC by jukomericki

When horizontal scaling feature is released for the cloud, we would also like to give our customers some information on how they can easily move their collection shards from their old nodes to their new nodes

2023-11-07 16:37 UTC, fabriziobonavita requested changes
Great! Left some suggestions

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +After scaling a cluster horizontally, the user can move shards from their old node to the new one to balance the memory and storage utilization of the nodes.
```suggestion
After scaling a cluster horizontally, you can move shards from your original nodes to the new ones to balance memory and storage utilization. 
```

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +NOTE: this guide is an example of moving shards from node 0, if the user wants to move shard from another
```suggestion
NOTE: this guide is an example of moving shards from node 0, if you want to move shards from another 
```

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +node they would need to change their cluster URL to `https://node-{source_node}-xyz-example.eu-central.aws.cloud.qdrant.io`
```suggestion
node you would need to change your cluster URL to `https://node-{source_node}-xyz-example.eu-central.aws.cloud.qdrant.io`
```

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +Firstly, after adding nodes confirm that new peers are added by running the following:
```suggestion
Firstly, after adding nodes confirm that new peers are present by running:
```

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +Afterwards the user needs to check the target collection cluster info. This gives insights of how many shards are on the node and its size. Note the `local_shards` from the return result and note a `
```suggestion
Afterwards you need to check the target collection cluster info. This gives insights of how many shards are on the node and its size. Note the `local_shards` from the return result and note a `shard_id` of the shard you want to move to another node.
```

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +This inititates a background shard move operation which doesn't affect the database performance. After the shard is moved the user
It can actually affect performance as it'll increase cpu on the target node

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +This inititates a background shard move operation which doesn't affect the database performance. After the shard is moved the user
```suggestion
This initiates a background shard move operation. After the shard is moved you
```

2023-11-07 16:37 UTC, fabriziobonavita commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +can confirm it by once again running the second step command (querying collection cluster info), and the user will notice that the shard has moved to another peer.
```suggestion
can confirm it by once again running the command from step two (querying collection cluster info), and you will notice that the shard has moved to another peer.
```

2023-11-20 16:56 UTC, bashofmann commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +NOTE: NOTE: this guide is an example of moving shards from node 0, if you want to move shards from another
```suggestion
NOTE: This guide is an example of moving shards from node 0, if you want to move shards from another 
```

2023-11-20 16:56 UTC, bashofmann commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +Firstly, after adding nodes confirm that new peers are present by running:
```suggestion
First, after adding nodes confirm that new peers are present by running:
```

2023-11-20 16:56 UTC, bashofmann commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +Note the `peer_ids` of the peers as they are needed for the last step of moving shards
```suggestion
Note the `peer_ids` of the peers as they are needed for the last step of moving shards.
```

2023-11-20 16:57 UTC, bashofmann commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +Afterwards you need to check the target collection cluster info. This gives insights of how many shards are on the node and its size. Note the `local_shards` from the return result and note a `shard_
```suggestion
Next, you need to check the target collection cluster info. This gives insights on how many shards are on a node and its size. Note the `local_shards` from the return result and note a `shard_id` of the shard you want to move to another node.
```

2023-11-20 16:58 UTC, bashofmann commented on qdrant-landing/content/documentation/cloud/cluster-scaling.md
> +This initiates a background shard move operation. After the shard is moved you can confirm it by once again running the command from step two (querying collection cluster info), and you will notice t
```suggestion
This initiates a background operation to move a shard. After the shard is moved, you can confirm the operation's success by once again running the command from step two (querying collection cluster info), and you will notice that the shard has moved to another peer.
```

2023-11-20 16:59 UTC, bashofmann commented
I proposed a couple changes to fix grammar and style.

2024-10-10 16:12 UTC, bashofmann commented
Not needed. This will be done automatically by cluster-manager in cloud.

2024-10-10 16:12 UTC, closed without merging