Mike Jang's proposed readability improvement
qdrant/landing_page pull request #400
Opened 2023-11-10 07:05 UTC by mjang

2023-11-10 08:39 UTC, timvisee approved these changes

2023-11-10 19:30 UTC, generall requested changes
I don't think that is correct interpretation of the original thought.

Vector databases are not directly useful for `Sentiment analysis` or `Speech recognition`.


Truthfully, the whole passage should be replaced with something more meaningful

2023-11-10 20:10 UTC, mjang commented
> I don't think that is correct interpretation of the original thought.
> 
> Vector databases are not directly useful for `Sentiment analysis` or `Speech recognition`.
> 
> Truthfully, the whole passage should be replaced with something more meaningful

Thank you @generall . Then I suggest that we close/replace this PR with an issue where we can discuss details.

You stated:

> Vector databases are not directly useful for `Sentiment analysis` or `Speech recognition`.

The current document states:

"...the data used to train a machine learning model to accomplish a task like sentiment analysis, speech recognition, object detection,..."

The difference is too subtle for all but the most careful reader. If we want to get into such detail, I believe that belongs somewhere other than the "Introduction."

![qdrant_intro1](https://github.com/qdrant/landing_page/assets/3287976/ec14e620-79e9-485c-9f64-a680263db299)

2023-11-16 12:13 UTC, mjang commented on qdrant-landing/content/documentation/overview/_index.md
> +- Object detection
We could link the example tasks to existing Qdrant use cases (taken from https://qdrant.tech/solutions/) 

```suggestion
- [Similar Image Search](https://food-discovery.qdrant.tech/)
- [Semantic Text Search](https://demo.qdrant.tech/)
- [Anamoly Detection](https://qdrant.tech/articles/detecting-coffee-anomalies/)
```

2023-11-16 12:15 UTC, mjang commented on qdrant-landing/content/documentation/overview/_index.md
> +- Object detection
Alternatively, if these examples are not appropriate, then we could remove them. After all, this is an introduction. Do either of these options make sense, @generall ?

2023-11-23 14:38 UTC, mjang commented
I've tried rewriting this in several ways to avoid the issues that @generall suggests. But they lead to other problems. So I'm closing this in favor of https://github.com/qdrant/landing_page/issues/422 .

2023-11-23 14:38 UTC, closed without merging