Add Discovery API documentation
qdrant/landing_page pull request #408
Opened 2023-11-15 15:49 UTC by coszio

Adds the `Discovery API` section to `search.md`

Pending: 
- [ ] add images

2023-11-27 16:13 UTC, kacperlukawski requested changes
Overall, it's a clear description. I suggested a small adjustment to the initial description (about the context).

2023-11-27 16:13 UTC, kacperlukawski commented on qdrant-landing/content/documentation/concepts/search.md
> +In this api, Qdrant introduces the concept of `context`, which is used for splitting the space, so that the space in which you search becomes constrained by the vectors you provide in the context. Th
```suggestion
In this API, Qdrant introduces the concept of `context`, which is used for splitting the space. Context is a set of positive-negative pairs. Each pair divides the space into positive and negative zones. In that mode, the search operation prefers points based on how many positive zones they belong to.

The interface for providing context is similar to the recommendation API (ids or raw vectors). Still, in this case, they need to be provided in the form of positive-negative pairs. 
```

2023-11-27 16:13 UTC, kacperlukawski commented on qdrant-landing/content/documentation/concepts/search.md
> +Using this kind of search, you can expect the output to not necessarily be around a single point, but rather, to be any point that isn’t closer to a negative example, which creates a constrained dive
```suggestion
Using this kind of search, you can expect the output to not necessarily be around a single point, but rather, to be any point that isn’t closer to a negative example, which creates a constrained diverse result. So, even when the API is not called [`recommend`](#recommendation-api), recommendation systems can also use this approach and adapt it for their specific use-cases.
```

2023-11-29 14:27 UTC, coszio commented on qdrant-landing/content/documentation/concepts/search.md
> +In this api, Qdrant introduces the concept of `context`, which is used for splitting the space, so that the space in which you search becomes constrained by the vectors you provide in the context. Th
Thanks! Applied suggestion

2023-11-29 14:27 UTC, coszio commented on qdrant-landing/content/documentation/concepts/search.md
> +Using this kind of search, you can expect the output to not necessarily be around a single point, but rather, to be any point that isn’t closer to a negative example, which creates a constrained dive
Thanks! Applied suggestion

2023-11-29 14:30 UTC, coszio commented
As per @generall request (which I agree), I moved recommend and discover to their own standalone page, I called it `Explore` so that we can later also include `diversity` there, but other suggestions are welcome.

2023-12-06 21:30 UTC, generall commented
ToDo:

- re-draw pictures using our style guidelines
- generate preview image for the new section

2023-12-06 22:31 UTC, generall approved these changes

2023-12-08 09:23 UTC, timvisee approved these changes

2023-12-08 09:55 UTC, merged