docs: Fondant integration docs
qdrant/landing_page pull request #421
Opened 2023-11-23 01:32 UTC by Anush008

This PR adds [FondantAI](https://fondant.ai/) to the integrations section.

2023-11-29 15:40 UTC, Anush008 commented
@kacperlukawski, review please.

2023-12-01 10:53 UTC, kacperlukawski requested changes
LGTM, just a minor change regarding the usage note

2023-12-01 10:53 UTC, kacperlukawski commented on qdrant-landing/content/documentation/integrations/fondant.md
> +https://qdrant.tech/documentation/concepts/collections/
```suggestion
A Qdrant collection has to be <a href="documentation/concepts/collections/">created in advance</a>
```

2023-12-01 12:17 UTC, kacperlukawski approved these changes

2023-12-01 12:18 UTC, merged