docs: N8N Qdrant blog
qdrant/landing_page pull request #506
Opened 2024-01-08 05:51 UTC by Anush008

This PR adds a blog about building a workflow using the new Qdrant N8N node.

2024-01-11 16:11 UTC, mjang requested changes
Your content is easy to read. It's at a "grade level 8" on the Flesch-Kincaid scale, which is impressive for AI!

While I've checked the wording and basic technical content, I have _not_ run your examples (too much to do)

2024-01-11 16:11 UTC, mjang commented on qdrant-landing/content/blog/qdrant-n8n.md
> +For this workflow, we'll use the following nodes.
```suggestion
For this workflow, we'll use the following nodes:
```

2024-01-11 16:11 UTC, mjang commented on qdrant-landing/content/blog/qdrant-n8n.md
> +The workflow use the following nodes
```suggestion
The workflow use the following nodes:
```

2024-01-11 16:11 UTC, mjang commented on qdrant-landing/content/blog/qdrant-n8n.md
> +- [Qdrant Node documentation](https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreqdrant/#qdrant-vector-store)
```suggestion
- [n8n Documentation](https://docs.n8n.io/)
- [n8n Qdrant Node documentation](https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreqdrant/#qdrant-vector-store)
```

2024-01-12 06:48 UTC, Anush008 commented on qdrant-landing/content/blog/qdrant-n8n.md
> +- [Qdrant Vector Store - Insert](https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreqdrant/#insert-documents): Configure with API key and collection name
https://github.com/qdrant/landing_page/pull/506/commits/7d75f005f6eaafc9103d679786842766fd44c857

2024-01-12 11:06 UTC, Anush008 commented on qdrant-landing/static/blog/qdrant-n8n/preview/social_preview.jpg
It is from the n8n integrations page(auto-generated for the all the integrations). So unfortunately, we can't have that updated.

2024-01-12 17:48 UTC, mjang approved these changes
LGTM from a TW PoV. Thanks @Anush008 !

2024-01-13 00:36 UTC, merged