Datatalk podcast plug with RAG Eval
qdrant/landing_page pull request #516
Opened 2024-01-11 09:28 UTC by atarora

Added DeepRec Event info too.

2024-01-11 16:27 UTC, mjang commented on qdrant-landing/content/blog/datatalk-club-podcast-plug.md
> +## Navigating challenges and innovations in search technologies
Adding header info. Please modify as you'd like:
```suggestion
title: "Navigating challenges and innovations in search technologies"
draft: false
slug: navigating-challenges-innovations
short_description: Podcast on search and LLM with Datatalks
description: <substitute>
date: <substitute publication date>
author: Atita Arora
featured: false
tags:
  - podcast
  - search
  - blog
  - retrieval-augmented generation
  - large language models
---

## Navigating challenges and innovations in search technologies
```

2024-01-12 15:54 UTC, generall requested changes
Please specify at least `preview_image`.

2024-01-12 15:54 UTC, generall commented on qdrant-landing/content/blog/datatalk-club-podcast-plug.md
> +date: 12.01.2024
the date should be specified in the format like this: `2022-09-26T15:39:53.751Z`

2024-01-12 16:56 UTC, atarora commented
> Please specify at least `preview_image`.

Done !

2024-01-12 17:22 UTC, mjang commented on qdrant-landing/content/blog/datatalk-club-podcast-plug.md
> +date: 12.01.2024T15:39:53.751Z
Hugo (doc tool) expects a different date format. This makes the article link appear at https://qdrant.tech/blog/

```suggestion
date: 2024-01-12T15:39:53.751Z
```

2024-01-12 18:38 UTC, mjang approved these changes
We discussed the draft in raw form before @atarora submitted this PR

2024-01-14 16:34 UTC, merged