Add Articles Page and Article-Post Page
qdrant/landing_page pull request #810
Opened 2024-04-12 10:31 UTC by nastyapash

2024-04-12 13:35 UTC, trean requested changes
Thank you for PR!
I left a couple of comments and proposed small changes through PR https://github.com/qdrant/landing_page/pull/812 (to avoid long explanations)

2024-04-12 13:35 UTC, trean commented on qdrant-landing/content/articles/_index.md
>  title: Articles
I think it's ok to replace the current title here

2024-04-12 14:10 UTC, nastyapash commented on qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html
> +              <div style="background-image: url({{ .Params.preview_dir }}/title.jpg)"></div>
Okay, I'll change it now! I used background property because I didn’t know what size the pictures could be, so I used the background-size: cover.

2024-04-12 15:00 UTC, nastyapash commented on qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html
> +              <div style="background-image: url({{ .Params.preview_dir }}/title.jpg)"></div>
@trean  For example, here the images have different heights If I change the height value, the aspect ratio of the image will change. What to do in this case?

<img width="659" alt="Снимок экрана 2024-04-12 в 17 56 22" src="https://github.com/qdrant/landing_page/assets/38438810/066156d1-03bc-4f09-aa5d-0b6547492269">

2024-04-12 15:02 UTC, nastyapash commented on qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html
> +              <div style="background-image: url({{ .Params.preview_dir }}/title.jpg)"></div>
Or I can use **object-fit: cover**, but it doesn't work in all browsers.

2024-04-12 16:03 UTC, trean commented on qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html
> +              <div style="background-image: url({{ .Params.preview_dir }}/title.jpg)"></div>
Oh, I see. All these picture files are generated automatically in CI and are supposed to have the same aspect ratio and if they do not it's an error in our script.
Let's assume that they are the same size and we will fix it later. For now, it's ok if they take whole `.post-preview` width, and if the picture is higher than `.post-preview` hide it with `overflow: hidden;`, if it's shorter - let it be.
Would this approach work for you?

2024-04-12 16:08 UTC, nastyapash commented on qdrant-landing/themes/qdrant-2024/layouts/partials/qdrant-articles-posts.html
> +              <div style="background-image: url({{ .Params.preview_dir }}/title.jpg)"></div>
Yes of course :) I'll do it now

2024-04-15 08:34 UTC, trean approved these changes

2024-04-15 20:31 UTC, merged