docs: Snowflake embeddings
qdrant/landing_page pull request #834
Opened 2024-04-18 07:03 UTC by Anush008

[PREVIEW]()

2024-04-19 09:02 UTC, kacperlukawski requested changes
Can we change the order of the languages? Python first, and then Typescript is a convention we keep everywhere.

2024-04-19 09:02 UTC, kacperlukawski commented on qdrant-landing/content/documentation/embeddings/snowflake.md
> +```
Could you please change the order? Python was usually presented as the first language, so it would be great to keep it consistent.

2024-04-19 13:20 UTC, kacperlukawski approved these changes

2024-05-06 12:17 UTC, merged

2024-05-06 12:17 UTC, Anush008 commented
Released https://github.com/qdrant/fastembed/releases/tag/v0.2.7.