Add Documentation page
qdrant/landing_page pull request #861
Opened 2024-05-01 08:47 UTC by nastyapash

2024-05-02 10:24 UTC, trean requested changes
Thank you for PR! 🚀 I left some change requests.

Also, do you have the latest version of the `new-design` branch here? Code snippets look like this in it.
![image](https://github.com/qdrant/landing_page/assets/7085263/a6365225-1641-432d-b8b1-f225eb86f4fb)

And here is how they look in the current branch (seems not to functioning)
![image](https://github.com/qdrant/landing_page/assets/7085263/beb9575c-974f-4396-bca9-b6b1634bc39c)

Normally, you don't need to do anything to add them, they already should work. Try to rebase your branch to the `new-design`.

2024-05-02 10:24 UTC, trean commented on qdrant-landing/themes/qdrant-2024/layouts/partials/docs-menu.html
> +{{ with (.Site.GetPage "/headless/docs-menu") }}
We need to generate this menu from the list of documentation pages, not from markdown. 
Can you use the file `qdrant-landing/themes/qdrant/layouts/partials/docs_sidebar.html` as a reference to create it? You may replace the existing HTML with your own, but please reuse the Hugo code. You don't need to rename your file.
If you encounter any issues, please let me know.

2024-05-02 10:24 UTC, trean commented on qdrant-landing/themes/qdrant-2024/layouts/partials/table-contents.html
> +{{ with (.Site.GetPage "/headless/table-contents") }}
We need to generate this from content, not from a markdown file. Here is an example: `qdrant-landing/themes/qdrant/layouts/partials/table_of_content.html`.
The `.TableOfContents` method returns an HTML list of content headings:
``` html
<nav id="TableOfContents">
  <ul>
    <li>
      <a href="/aaa">Heading h1</a>
    </li>
    <!-- and so on -->
  </ul>
</nav>
```
[Example here](https://qdrant.tech/documentation/)

2024-05-03 13:54 UTC, trean commented
@nastyapash Thank you so much for the update! 🎉 

There are only two small things to finish this section:

1. The docs menu does not expand on mobile anymore, maybe some id or class got lost?
![image](https://github.com/qdrant/landing_page/assets/7085263/fe7e8724-fb57-43cc-886a-d5efba836058)

2. Could you add `text-overflow: ellipsis;` and indentation for nested links to the table of contents, see this page as an example https://qdrant.tech/documentation/guides/quantization/ 
![image](https://github.com/qdrant/landing_page/assets/7085263/59dc8157-7854-481f-ad86-f2fd7ab154fa)

2024-05-03 15:10 UTC, nastyapash commented
@trean I added text trim and padding for links in the table of contents!

But opening/closing the menu works for me in the mobile version. This happens using the id #sidebar-toggle, the code is in the file qdrant-landing/themes/qdrant-2024/layouts/partials/js.html

2024-05-03 15:37 UTC, trean commented
> @trean I added text trim and padding for links in the table of contents!
> 
> But opening/closing the menu works for me in the mobile version. This happens using the id #sidebar-toggle, the code is in the file qdrant-landing/themes/qdrant-2024/layouts/partials/js.html

I see now :-) it doesn't work because it uses jQuery. We won't have jQuery in this theme. Perhaps you have it locally somehow and this why it works on your machine. Using vanilla js will fix the problem.

The table of contents looks good, thanks!

2024-05-03 15:39 UTC, trean commented
@nastyapash oops, one more tiny thing
![Screenshot 2024-05-03 at 17 38 34](https://github.com/qdrant/landing_page/assets/7085263/f81f41b4-ebc0-4176-b740-d7ebf21405e0)

2024-05-03 16:44 UTC, trean approved these changes

2024-05-03 17:26 UTC, merged